services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3001
    restart: unless-stopped 